# Merge Years 2012-2019

### Import pandas package

In [1]:
import pandas as pd

## Import all datasets needed for merge

In [5]:
nfl2012_2018 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2012_2018merge.csv')
off2019 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2019_offense.csv')
def2019 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2019_defense.csv')
wl2019 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_win_lose/NFL_2019_wl.csv')

In [6]:
nfl2012_2018.head()

,Unnamed: 0,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
0,0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,...,3213,200.8,5405,337.8,2012,5,11,0,No,No
1,1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,...,3878,242.4,5849,365.6,2012,13,3,0,No,No
2,2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,...,3650,228.1,5615,350.9,2012,10,6,0,Yes,Yes
3,3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,...,3473,217.1,5806,362.9,2012,6,10,0,No,No
4,4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,...,3568,223.0,5329,333.1,2012,7,9,0,No,No

In [7]:
off2019.head()

,Unnamed: 0,Team,2019 Off Tot Pts,2019 Off Pts/G,2019 Off RushYds,2019 Off RYds/G,2019 Off PassYds,2019 Off PYds/G,2019 Off TotYds,2019 Off Yds/G
0,20,Arizona CardinalsArizona,361,22.6,1990,124.4,3477,217.3,5467,341.7
1,4,Atlanta FalconsAtlanta,381,23.8,1361,85.1,4714,294.6,6075,379.7
2,1,Baltimore RavensBaltimore,531,33.2,3296,206.0,3225,201.6,6521,407.6
3,23,Buffalo BillsBuffalo,314,19.6,2054,128.4,3229,201.8,5283,330.2
4,18,Carolina PanthersCarolina,340,21.2,1819,113.7,3650,228.1,5469,341.8

In [8]:
def2019.head()

,Unnamed: 0,Team,2019 Def Tot/Pts,2019 Def Pts/G,2019 Def RushYds,2019 Def RYds/G,2019 Def PassYds,2019 Def PYds/G,2019 Def TotYds,2019 Def Yds/G
0,31,Arizona CardinalsArizona,442,27.6,1922,120.1,4510,281.9,6432,402.0
1,19,Atlanta FalconsAtlanta,399,24.9,1775,110.9,3918,244.9,5693,355.8
2,3,Baltimore RavensBaltimore,282,17.6,1494,93.4,3315,207.2,4809,300.6
3,2,Buffalo BillsBuffalo,259,16.2,1649,103.1,3123,195.2,4772,298.2
4,22,Carolina PanthersCarolina,470,29.4,2296,143.5,3696,231.0,5992,374.5

In [9]:
wl2019.head()

   Unnamed: 0               Team  Wins  Losses  Tie Superbowl SB Win  Year
0           4  Arizona Cardinals     5      10    1        No     No  2019
1          10    Atlanta Falcons     7       9    0        No     No  2019
2          31   Baltimore Ravens    14       2    0        No     No  2019
3          22      Buffalo Bills    10       6    0        No     No  2019
4           5  Carolina Panthers     5      11    0        No     No  2019

### Drop unnamed column in all datasets

In [10]:
nfl2012_2018 = nfl2012_2018.iloc[:, 1:]
off2019 = off2019.iloc[:, 1:]
def2019 = def2019.iloc[:, 1:]
wl2019 = wl2019.iloc[:, 1:]

In [11]:
nfl2012_2018.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,...,3213,200.8,5405,337.8,2012,5,11,0,No,No
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,...,3878,242.4,5849,365.6,2012,13,3,0,No,No
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,...,3650,228.1,5615,350.9,2012,10,6,0,Yes,Yes
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,...,3473,217.1,5806,362.9,2012,6,10,0,No,No
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,...,3568,223.0,5329,333.1,2012,7,9,0,No,No

In [12]:
off2019.head()

,Team,2019 Off Tot Pts,2019 Off Pts/G,2019 Off RushYds,2019 Off RYds/G,2019 Off PassYds,2019 Off PYds/G,2019 Off TotYds,2019 Off Yds/G
0,Arizona CardinalsArizona,361,22.6,1990,124.4,3477,217.3,5467,341.7
1,Atlanta FalconsAtlanta,381,23.8,1361,85.1,4714,294.6,6075,379.7
2,Baltimore RavensBaltimore,531,33.2,3296,206.0,3225,201.6,6521,407.6
3,Buffalo BillsBuffalo,314,19.6,2054,128.4,3229,201.8,5283,330.2
4,Carolina PanthersCarolina,340,21.2,1819,113.7,3650,228.1,5469,341.8

In [13]:
def2019.head()

,Team,2019 Def Tot/Pts,2019 Def Pts/G,2019 Def RushYds,2019 Def RYds/G,2019 Def PassYds,2019 Def PYds/G,2019 Def TotYds,2019 Def Yds/G
0,Arizona CardinalsArizona,442,27.6,1922,120.1,4510,281.9,6432,402.0
1,Atlanta FalconsAtlanta,399,24.9,1775,110.9,3918,244.9,5693,355.8
2,Baltimore RavensBaltimore,282,17.6,1494,93.4,3315,207.2,4809,300.6
3,Buffalo BillsBuffalo,259,16.2,1649,103.1,3123,195.2,4772,298.2
4,Carolina PanthersCarolina,470,29.4,2296,143.5,3696,231.0,5992,374.5

In [14]:
wl2019.head()

                Team  Wins  Losses  Tie Superbowl SB Win  Year
0  Arizona Cardinals     5      10    1        No     No  2019
1    Atlanta Falcons     7       9    0        No     No  2019
2   Baltimore Ravens    14       2    0        No     No  2019
3      Buffalo Bills    10       6    0        No     No  2019
4  Carolina Panthers     5      11    0        No     No  2019

### Rename columns in off/def data

In [15]:
offense2019 = off2019.rename(columns ={"2019 Off Tot Pts": "Off Tot/Pts", "2019 Off Pts/G": "Off Pts/G",
                                                     "2019 Off RushYds": "Off RushYds", "2019 Off RYds/G": "Off RYds/G",
                                                     "2019 Off PassYds": "Off PassYds", "2019 Off PYds/G": "Off PYds/G",
                                                     "2019 Off TotYds": "Off TotYds", "2019 Off Yds/G": "Off Yds/G"})
defense2019 = def2019.rename(columns ={"2019 Def Tot/Pts": "Def Tot/Pts", "2019 Def Pts/G": "Def Pts/G",
                                                     "2019 Def RushYds": "Def RushYds", "2019 Def RYds/G": "Def RYds/G",
                                                     "2019 Def PassYds": "Def PassYds", "2019 Def PYds/G": "Def PYds/G",
                                                     "2019 Def TotYds": "Def TotYds", "2019 Def Yds/G": "Def Yds/G"})

In [16]:
offense2019.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G
0,Arizona CardinalsArizona,361,22.6,1990,124.4,3477,217.3,5467,341.7
1,Atlanta FalconsAtlanta,381,23.8,1361,85.1,4714,294.6,6075,379.7
2,Baltimore RavensBaltimore,531,33.2,3296,206.0,3225,201.6,6521,407.6
3,Buffalo BillsBuffalo,314,19.6,2054,128.4,3229,201.8,5283,330.2
4,Carolina PanthersCarolina,340,21.2,1819,113.7,3650,228.1,5469,341.8

In [17]:
defense2019.head()

,Team,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
0,Arizona CardinalsArizona,442,27.6,1922,120.1,4510,281.9,6432,402.0
1,Atlanta FalconsAtlanta,399,24.9,1775,110.9,3918,244.9,5693,355.8
2,Baltimore RavensBaltimore,282,17.6,1494,93.4,3315,207.2,4809,300.6
3,Buffalo BillsBuffalo,259,16.2,1649,103.1,3123,195.2,4772,298.2
4,Carolina PanthersCarolina,470,29.4,2296,143.5,3696,231.0,5992,374.5

### Merge Offense and Defense Data

In [18]:
off_def2019 = pd.merge(offense2019, defense2019, on='Team')

In [20]:
off_def2019.head(32)

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
0,Arizona CardinalsArizona,361,22.6,1990,124.4,3477,217.3,5467,341.7,442,27.6,1922,120.1,4510,281.9,6432,402.0
1,Atlanta FalconsAtlanta,381,23.8,1361,85.1,4714,294.6,6075,379.7,399,24.9,1775,110.9,3918,244.9,5693,355.8
2,Baltimore RavensBaltimore,531,33.2,3296,206.0,3225,201.6,6521,407.6,282,17.6,1494,93.4,3315,207.2,4809,300.6
3,Buffalo BillsBuffalo,314,19.6,2054,128.4,3229,201.8,5283,330.2,259,16.2,1649,103.1,3123,195.2,4772,298.2
4,Carolina PanthersCarolina,340,21.2,1819,113.7,3650,228.1,5469,341.8,470,29.4,2296,143.5,3696,231.0,5992,374.5
5,Chicago BearsChicago,280,17.5,1458,91.1,3291,205.7,4749,296.8,298,18.6,1632,102.0,3554,222.1,5186,324.1
6,Cincinnati BengalsCincinnati,279,17.4,1517,94.8,3652,228.2,5169,323.1,420,26.2,2382,148.9,3917,244.8,6299,393.7
7,Cleveland BrownsCleveland,335,20.9,1901,118.8,3554,222.1,5455,340.9,393,24.6,2315,144.7,3470,216.9,5785,361.6
8,Dallas CowboysDallas,434,27.1,2153,134.6,4751,296.9,6904,431.5,321,20.1,1656,103.5,3576,223.5,5232,327.0
9,Denver BroncosDenver,282,17.6,1662,103.9,3115,194.7,4777,298.6,316,19.8,1783,111.4,3609,225.6,5392,337.0
10,Detroit LionsDetroit,341,21.3,1649,103.1,3900,243.8,5549,346.8,423,26.4,1855,115.9,4551,284.4,6406,400.4
11,Green Bay PackersGreen Bay,376,23.5,1795,112.2,3733,233.3,5528,345.5,313,19.6,1921,120.1,3721,232.6,5642,352.6
12,Houston TexansHouston,378,23.6,2009,125.6,3783,236.4,5792,362.0,385,24.1,1937,121.1,4276,267.2,6213,388.3
13,Indianapolis ColtsIndianapolis,361,22.6,2130,133.1,3108,194.2,5238,327.4,373,23.3,1567,97.9,3982,248.9,5549,346.8
14,Jacksonville JaguarsJacksonville,300,18.8,1708,106.8,3760,235.0,5468,341.8,397,24.8,2229,139.3,3778,236.1,6007,375.4
15,Kansas City ChiefsKansas City,451,28.2,1569,98.1,4498,281.1,6067,379.2,308,19.2,2051,128.2,3543,221.4,5594,349.6
16,Los Angeles ChargersLA Chargers,337,21.1,1453,90.8,4426,276.6,5879,367.4,345,21.6,1805,112.8,3204,200.2,5009,313.1
17,Los Angeles RamsLA Rams,394,24.6,1499,93.7,4499,281.2,5998,374.9,364,22.8,1809,113.1,3625,226.6,5434,339.6
18,Miami DolphinsMiami,306,19.1,1156,72.2,3804,237.8,4960,310.0,494,30.9,2166,135.4,4198,262.4,6364,397.8
19,Minnesota VikingsMinnesota,407,25.4,2133,133.3,3523,220.2,5656,353.5,303,18.9,1728,108.0,3737,233.6,5465,341.6
20,New England PatriotsNew England,420,26.2,1703,106.4,3961,247.6,5664,354.0,225,14.1,1528,95.5,2886,180.4,4414,275.9
21,New Orleans SaintsNew Orleans,458,28.6,1738,108.6,4244,265.2,5982,373.9,341,21.3,1461,91.3,3868,241.8,5329,333.1
22,New York GiantsNY Giants,341,21.3,1685,105.3,3731,233.2,5416,338.5,451,28.2,1812,113.2,4225,264.1,6037,377.3
23,New York JetsNY Jets,276,17.2,1257,78.6,3111,194.4,4368,273.0,359,22.4,1391,86.9,3779,236.2,5170,323.1
24,Oakland RaidersOakland,313,19.6,1893,118.3,3926,245.4,5819,363.7,419,26.2,1570,98.1,4107,256.7,5677,354.8
25,Philadelphia EaglesPhiladelphia,385,24.1,1939,121.2,3833,239.6,5772,360.8,354,22.1,1442,90.1,3865,241.6,5307,331.7
26,Pittsburgh SteelersPittsburgh,289,18.1,1447,90.4,2981,186.3,4428,276.8,303,18.9,1753,109.6,3113,194.6,4866,304.1
27,San Francisco 49ersSan Francisco,479,29.9,2305,144.1,3792,237.0,6097,381.1,310,19.4,1802,112.6,2707,169.2,4509,281.8
28,Seattle SeahawksSeattle,405,25.3,2200,137.5,3791,236.9,5991,374.4,398,24.9,1883,117.7,4223,263.9,6106,381.6
29,Tampa Bay BuccaneersTampa Bay,458,28.6,1521,95.1,4845,302.8,6366,397.9,449,28.1,1181,73.8,4322,270.1,5503,343.9
30,Tennessee TitansTennessee,402,25.1,2223,138.9,3582,223.9,5805,362.8,331,20.7,1672,104.5,4080,255.0,5752,359.5
31,Washington RedskinsWashington,266,16.6,1583,98.9,2812,175.8,4395,274.7,435,27.2,2339,146.2,3823,238.9,6162,385.1

### Rename Teams to match merge data

In [21]:
teamnames19 = {'Arizona CardinalsArizona': 'Arizona Cardinals', 'Atlanta FalconsAtlanta': 'Atlanta Falcons', 
             'Baltimore RavensBaltimore': 'Baltimore Ravens', 'Buffalo BillsBuffalo': 'Buffalo Bills',
            'Carolina PanthersCarolina': 'Carolina Panthers', 'Chicago BearsChicago': 'Chicago Bears',
            'Cincinnati BengalsCincinnati': 'Cincinnati Bengals', 'Cleveland BrownsCleveland': 'Cleveland Browns',
            'Dallas CowboysDallas': 'Dallas Cowboys', 'Denver BroncosDenver': 'Denver Broncos', 
             'Detroit LionsDetroit': 'Detroit Lions', 'Green Bay PackersGreen Bay': 'Green Bay Packers',
            'Houston TexansHouston': 'Houston Texans', 'Indianapolis ColtsIndianapolis': 'Indianapolis Colts',
            'Jacksonville JaguarsJacksonville': 'Jacksonville Jaguars', 'Kansas City ChiefsKansas City': 'Kansas City Chiefs',
            'Los Angeles ChargersLA Chargers': 'Los Angeles Chargers', 'Los Angeles RamsLA Rams': 'Los Angeles Rams',
            'Miami DolphinsMiami': 'Miami Dolphins', 'Minnesota VikingsMinnesota': 'Minnesota Vikings', 
            'New England PatriotsNew England': 'New England Patriots', 'New Orleans SaintsNew Orleans': 'New Orleans Saints',
            'New York GiantsNY Giants': 'New York Giants', 'New York JetsNY Jets': 'New York Jets', 
            'Oakland RaidersOakland': 'Las Vegas Raiders', 'Philadelphia EaglesPhiladelphia': 'Philadelphia Eagles',
            'Pittsburgh SteelersPittsburgh': 'Pittsburgh Steelers',
            'San Francisco 49ersSan Francisco': 'San Francisco 49ers', 'Seattle SeahawksSeattle': 'Seattle Seahawks', 
            'Tampa Bay BuccaneersTampa Bay': 'Tampa Bay Buccaneers', 'Tennessee TitansTennessee': 'Tennessee Titans',
            'Washington RedskinsWashington': 'Washington Commanders'}
off_def2019['Team'] = off_def2019['Team'].replace(teamnames19)

In [22]:
off_def2019.tail(16)

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
16,Los Angeles Chargers,337,21.1,1453,90.8,4426,276.6,5879,367.4,345,21.6,1805,112.8,3204,200.2,5009,313.1
17,Los Angeles Rams,394,24.6,1499,93.7,4499,281.2,5998,374.9,364,22.8,1809,113.1,3625,226.6,5434,339.6
18,Miami Dolphins,306,19.1,1156,72.2,3804,237.8,4960,310.0,494,30.9,2166,135.4,4198,262.4,6364,397.8
19,Minnesota Vikings,407,25.4,2133,133.3,3523,220.2,5656,353.5,303,18.9,1728,108.0,3737,233.6,5465,341.6
20,New England Patriots,420,26.2,1703,106.4,3961,247.6,5664,354.0,225,14.1,1528,95.5,2886,180.4,4414,275.9
21,New Orleans Saints,458,28.6,1738,108.6,4244,265.2,5982,373.9,341,21.3,1461,91.3,3868,241.8,5329,333.1
22,New York Giants,341,21.3,1685,105.3,3731,233.2,5416,338.5,451,28.2,1812,113.2,4225,264.1,6037,377.3
23,New York Jets,276,17.2,1257,78.6,3111,194.4,4368,273.0,359,22.4,1391,86.9,3779,236.2,5170,323.1
24,Las Vegas Raiders,313,19.6,1893,118.3,3926,245.4,5819,363.7,419,26.2,1570,98.1,4107,256.7,5677,354.8
25,Philadelphia Eagles,385,24.1,1939,121.2,3833,239.6,5772,360.8,354,22.1,1442,90.1,3865,241.6,5307,331.7
26,Pittsburgh Steelers,289,18.1,1447,90.4,2981,186.3,4428,276.8,303,18.9,1753,109.6,3113,194.6,4866,304.1
27,San Francisco 49ers,479,29.9,2305,144.1,3792,237.0,6097,381.1,310,19.4,1802,112.6,2707,169.2,4509,281.8
28,Seattle Seahawks,405,25.3,2200,137.5,3791,236.9,5991,374.4,398,24.9,1883,117.7,4223,263.9,6106,381.6
29,Tampa Bay Buccaneers,458,28.6,1521,95.1,4845,302.8,6366,397.9,449,28.1,1181,73.8,4322,270.1,5503,343.9
30,Tennessee Titans,402,25.1,2223,138.9,3582,223.9,5805,362.8,331,20.7,1672,104.5,4080,255.0,5752,359.5
31,Washington Commanders,266,16.6,1583,98.9,2812,175.8,4395,274.7,435,27.2,2339,146.2,3823,238.9,6162,385.1

### Put Dataset in Team Ascending Order

In [23]:
off_def2019 = off_def2019.sort_values("Team")

In [24]:
off_def2019.tail(16)

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
24,Las Vegas Raiders,313,19.6,1893,118.3,3926,245.4,5819,363.7,419,26.2,1570,98.1,4107,256.7,5677,354.8
16,Los Angeles Chargers,337,21.1,1453,90.8,4426,276.6,5879,367.4,345,21.6,1805,112.8,3204,200.2,5009,313.1
17,Los Angeles Rams,394,24.6,1499,93.7,4499,281.2,5998,374.9,364,22.8,1809,113.1,3625,226.6,5434,339.6
18,Miami Dolphins,306,19.1,1156,72.2,3804,237.8,4960,310.0,494,30.9,2166,135.4,4198,262.4,6364,397.8
19,Minnesota Vikings,407,25.4,2133,133.3,3523,220.2,5656,353.5,303,18.9,1728,108.0,3737,233.6,5465,341.6
20,New England Patriots,420,26.2,1703,106.4,3961,247.6,5664,354.0,225,14.1,1528,95.5,2886,180.4,4414,275.9
21,New Orleans Saints,458,28.6,1738,108.6,4244,265.2,5982,373.9,341,21.3,1461,91.3,3868,241.8,5329,333.1
22,New York Giants,341,21.3,1685,105.3,3731,233.2,5416,338.5,451,28.2,1812,113.2,4225,264.1,6037,377.3
23,New York Jets,276,17.2,1257,78.6,3111,194.4,4368,273.0,359,22.4,1391,86.9,3779,236.2,5170,323.1
25,Philadelphia Eagles,385,24.1,1939,121.2,3833,239.6,5772,360.8,354,22.1,1442,90.1,3865,241.6,5307,331.7
26,Pittsburgh Steelers,289,18.1,1447,90.4,2981,186.3,4428,276.8,303,18.9,1753,109.6,3113,194.6,4866,304.1
27,San Francisco 49ers,479,29.9,2305,144.1,3792,237.0,6097,381.1,310,19.4,1802,112.6,2707,169.2,4509,281.8
28,Seattle Seahawks,405,25.3,2200,137.5,3791,236.9,5991,374.4,398,24.9,1883,117.7,4223,263.9,6106,381.6
29,Tampa Bay Buccaneers,458,28.6,1521,95.1,4845,302.8,6366,397.9,449,28.1,1181,73.8,4322,270.1,5503,343.9
30,Tennessee Titans,402,25.1,2223,138.9,3582,223.9,5805,362.8,331,20.7,1672,104.5,4080,255.0,5752,359.5
31,Washington Commanders,266,16.6,1583,98.9,2812,175.8,4395,274.7,435,27.2,2339,146.2,3823,238.9,6162,385.1

### Merge with Win/Loss Data

In [25]:
nfl2019 = pd.merge(off_def2019, wl2019, on="Team")

In [26]:
nfl2019.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Wins,Losses,Tie,Superbowl,SB Win,Year
0,Arizona Cardinals,361,22.6,1990,124.4,3477,217.3,5467,341.7,442,...,4510,281.9,6432,402.0,5,10,1,No,No,2019
1,Atlanta Falcons,381,23.8,1361,85.1,4714,294.6,6075,379.7,399,...,3918,244.9,5693,355.8,7,9,0,No,No,2019
2,Baltimore Ravens,531,33.2,3296,206.0,3225,201.6,6521,407.6,282,...,3315,207.2,4809,300.6,14,2,0,No,No,2019
3,Buffalo Bills,314,19.6,2054,128.4,3229,201.8,5283,330.2,259,...,3123,195.2,4772,298.2,10,6,0,No,No,2019
4,Carolina Panthers,340,21.2,1819,113.7,3650,228.1,5469,341.8,470,...,3696,231.0,5992,374.5,5,11,0,No,No,2019

### Save Dataset to Mac for future use

In [27]:
nfl2019.to_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2019complete.csv')

### Merge 2012-2019 Data

In [28]:
nfl2012_2019 = pd.concat([nfl2012_2018, nfl2019], axis=0, join='outer', ignore_index='True')

In [29]:
nfl2012_2019.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,...,3213,200.8,5405,337.8,2012,5,11,0,No,No
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,...,3878,242.4,5849,365.6,2012,13,3,0,No,No
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,...,3650,228.1,5615,350.9,2012,10,6,0,Yes,Yes
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,...,3473,217.1,5806,362.9,2012,6,10,0,No,No
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,...,3568,223.0,5329,333.1,2012,7,9,0,No,No

In [30]:
nfl2012_2019.tail()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
250,San Francisco 49ers,479,29.9,2305,144.1,3792,237.0,6097,381.1,310,...,2707,169.2,4509,281.8,2019,13,3,0,Yes,No
251,Seattle Seahawks,405,25.3,2200,137.5,3791,236.9,5991,374.4,398,...,4223,263.9,6106,381.6,2019,11,5,0,No,No
252,Tampa Bay Buccaneers,458,28.6,1521,95.1,4845,302.8,6366,397.9,449,...,4322,270.1,5503,343.9,2019,7,9,0,No,No
253,Tennessee Titans,402,25.1,2223,138.9,3582,223.9,5805,362.8,331,...,4080,255.0,5752,359.5,2019,9,7,0,No,No
254,Washington Commanders,266,16.6,1583,98.9,2812,175.8,4395,274.7,435,...,3823,238.9,6162,385.1,2019,3,13,0,No,No

### Save Dataset to Mac for future use

In [31]:
nfl2012_2019.to_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2012_2019merge.csv')