# Final Project Merging Data

### Import packages

In [1]:
import pandas as pd

### Import 2012 Offense & Defense Datasets

In [2]:
off2012 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2012_offense.csv')

In [3]:
def2012 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2012_defense.csv')

In [4]:
off2012.head()

,Unnamed: 0,Team,TotPts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G
0,31,Arizona CardinalsArizona,250,15.6,1204,75.2,3005,187.8,4209,263.1
1,7,Atlanta FalconsAtlanta,419,26.2,1397,87.3,4509,281.8,5906,369.1
2,15,Baltimore RavensBaltimore,398,24.9,1901,118.8,3739,233.7,5640,352.5
3,18,Buffalo BillsBuffalo,344,21.5,2217,138.6,3269,204.3,5486,342.9
4,11,Carolina PanthersCarolina,357,22.3,2088,130.5,3683,230.2,5771,360.7

In [5]:
def2012.head()

,Unnamed: 0,Team,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
0,11,Arizona CardinalsArizona,357,22.3,2192,137.0,3213,200.8,5405,337.8
1,23,Atlanta FalconsAtlanta,299,18.7,1971,123.2,3878,242.4,5849,365.6
2,16,Baltimore RavensBaltimore,344,21.5,1965,122.8,3650,228.1,5615,350.9
3,21,Buffalo BillsBuffalo,435,27.2,2333,145.8,3473,217.1,5806,362.9
4,9,Carolina PanthersCarolina,363,22.7,1761,110.1,3568,223.0,5329,333.1

### Drop unnamed column in both datasets

In [8]:
off2012 = off2012.iloc[:, 1:]

In [9]:
off2012.head()

,Team,TotPts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G
0,Arizona CardinalsArizona,250,15.6,1204,75.2,3005,187.8,4209,263.1
1,Atlanta FalconsAtlanta,419,26.2,1397,87.3,4509,281.8,5906,369.1
2,Baltimore RavensBaltimore,398,24.9,1901,118.8,3739,233.7,5640,352.5
3,Buffalo BillsBuffalo,344,21.5,2217,138.6,3269,204.3,5486,342.9
4,Carolina PanthersCarolina,357,22.3,2088,130.5,3683,230.2,5771,360.7

In [10]:
def2012 = def2012.iloc[:, 1:]

In [11]:
def2012.head()

,Team,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
0,Arizona CardinalsArizona,357,22.3,2192,137.0,3213,200.8,5405,337.8
1,Atlanta FalconsAtlanta,299,18.7,1971,123.2,3878,242.4,5849,365.6
2,Baltimore RavensBaltimore,344,21.5,1965,122.8,3650,228.1,5615,350.9
3,Buffalo BillsBuffalo,435,27.2,2333,145.8,3473,217.1,5806,362.9
4,Carolina PanthersCarolina,363,22.7,1761,110.1,3568,223.0,5329,333.1

### Rename offense data total pts column to have a year

In [13]:
offense2012 = off2012.rename(columns ={"TotPts": "2012 Off Tot Pts"})

In [14]:
offense2012.head()

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G
0,Arizona CardinalsArizona,250,15.6,1204,75.2,3005,187.8,4209,263.1
1,Atlanta FalconsAtlanta,419,26.2,1397,87.3,4509,281.8,5906,369.1
2,Baltimore RavensBaltimore,398,24.9,1901,118.8,3739,233.7,5640,352.5
3,Buffalo BillsBuffalo,344,21.5,2217,138.6,3269,204.3,5486,342.9
4,Carolina PanthersCarolina,357,22.3,2088,130.5,3683,230.2,5771,360.7

### Merge 2012 Offense and Defense into one dataset

In [15]:
off_def2012 = pd.merge(offense2012, def2012)

In [16]:
off_def2012.head()

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
0,Arizona CardinalsArizona,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,22.3,2192,137.0,3213,200.8,5405,337.8
1,Atlanta FalconsAtlanta,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,18.7,1971,123.2,3878,242.4,5849,365.6
2,Baltimore RavensBaltimore,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,21.5,1965,122.8,3650,228.1,5615,350.9
3,Buffalo BillsBuffalo,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,27.2,2333,145.8,3473,217.1,5806,362.9
4,Carolina PanthersCarolina,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,22.7,1761,110.1,3568,223.0,5329,333.1

In [19]:
off_def2012.tail()

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
27,Seattle SeahawksSeattle,412,25.8,2579,161.2,3031,189.4,5610,350.6,245,15.3,1649,103.1,3250,203.1,4899,306.2
28,St. Louis RamsSt. Louis,299,18.7,1714,107.1,3550,221.9,5264,329.0,348,21.8,1880,117.5,3602,225.1,5482,342.6
29,Tampa Bay BuccaneersTampa Bay,389,24.3,1837,114.8,3983,248.9,5820,363.8,394,24.6,1320,82.5,4758,297.4,6078,379.9
30,Tennessee TitansTennessee,330,20.6,1687,105.4,3323,207.7,5010,313.1,471,29.4,2035,127.2,3964,247.8,5999,374.9
31,Washington RedskinsWashington,436,27.2,2709,169.3,3422,213.9,6131,383.2,388,24.2,1532,95.8,4511,281.9,6043,377.7

### Import 2012 Win/Loss Dataset

In [20]:
wl2012 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_win_lose/NFL2012_wl.csv')

In [21]:
wl2012.head()

,Unnamed: 0,Team,2012 Wins,2012 Loss,2012 Tie,2012 Superbowl,2012 SB Win
0,5,Arizona Cardinals,5,11,0,No,No
1,30,Atlanta Falcons,13,3,0,No,No
2,19,Baltimore Ravens,10,6,0,Yes,Yes
3,7,Buffalo Bills,6,10,0,No,No
4,10,Carolina Panthers,7,9,0,No,No

### Drop unnamed column

In [22]:
wl2012 = wl2012.iloc[:, 1:]

In [30]:
wl2012.head(32)

,Team,2012 Wins,2012 Loss,2012 Tie,2012 Superbowl,2012 SB Win
0,Arizona Cardinals,5,11,0,No,No
1,Atlanta Falcons,13,3,0,No,No
2,Baltimore Ravens,10,6,0,Yes,Yes
3,Buffalo Bills,6,10,0,No,No
4,Carolina Panthers,7,9,0,No,No
5,Chicago Bears,10,6,0,No,No
6,Cincinnati Bengals,10,6,0,No,No
7,Cleveland Browns,5,11,0,No,No
8,Dallas Cowboys,8,8,0,No,No
9,Denver Broncos,13,3,0,No,No
10,Detroit Lions,4,12,0,No,No
11,Green Bay Packers,11,5,0,No,No
12,Houston Texans,12,4,0,No,No
13,Indianapolis Colts,11,5,0,No,No
14,Jacksonville Jaguars,2,14,0,No,No
15,Kansas City Chiefs,2,14,0,No,No
16,Las Vegas Raiders,4,12,0,No,No
17,Los Angeles Chargers,7,9,0,NoNo,NoNo
18,Los Angeles Rams,7,8,1,No,No
19,Miami Dolphins,7,9,0,No,No
20,Minnesota Vikings,10,6,0,No,No
21,New England Patriots,12,4,0,No,No
22,New Orleans Saints,7,9,0,No,No
23,New York Giants,9,7,0,No,No
24,New York Jets,6,10,0,No,No
25,Philadelphia Eagles,4,12,0,No,No
26,Pittsburgh Steelers,8,8,0,No,No
27,San Francisco 49ers,11,4,1,Yes,No
28,Seattle Seahawks,11,5,0,No,No
29,Tampa Bay Buccaneers,7,9,0,No,No
30,Tennessee Titans,6,10,0,No,No
31,Washington Commanders,10,6,0,No,No

In [31]:
off_def2012.head(32)

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
0,Arizona CardinalsArizona,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,22.3,2192,137.0,3213,200.8,5405,337.8
1,Atlanta FalconsAtlanta,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,18.7,1971,123.2,3878,242.4,5849,365.6
2,Baltimore RavensBaltimore,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,21.5,1965,122.8,3650,228.1,5615,350.9
3,Buffalo BillsBuffalo,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,27.2,2333,145.8,3473,217.1,5806,362.9
4,Carolina PanthersCarolina,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,22.7,1761,110.1,3568,223.0,5329,333.1
5,Chicago BearsChicago,375,23.4,1970,123.1,2999,187.4,4969,310.6,277,17.3,1627,101.7,3423,213.9,5050,315.6
6,Cincinnati BengalsCincinnati,391,24.4,1745,109.1,3578,223.6,5323,332.7,320,20.0,1715,107.2,3400,212.5,5115,319.7
7,Cleveland BrownsCleveland,302,18.9,1593,99.6,3435,214.7,5028,314.2,368,23.0,1898,118.6,3923,245.2,5821,363.8
8,Dallas CowboysDallas,376,23.5,1265,79.1,4729,295.6,5994,374.6,400,25.0,2003,125.2,3684,230.2,5687,355.4
9,Denver BroncosDenver,481,30.1,1832,114.5,4534,283.4,6366,397.9,289,18.1,1458,91.1,3194,199.6,4652,290.8
10,Detroit LionsDetroit,372,23.2,1613,100.8,4927,307.9,6540,408.8,437,27.3,1889,118.1,3569,223.1,5458,341.1
11,Green Bay PackersGreen Bay,433,27.1,1702,106.4,4049,253.1,5751,359.4,336,21.0,1896,118.5,3492,218.2,5388,336.8
12,Houston TexansHouston,416,26.0,2123,132.7,3830,239.4,5953,372.1,331,20.7,1560,97.5,3612,225.8,5172,323.2
13,Indianapolis ColtsIndianapolis,357,22.3,1671,104.4,4128,258.0,5799,362.4,387,24.2,2200,137.5,3788,236.8,5988,374.2
14,Jacksonville JaguarsJacksonville,255,15.9,1369,85.6,3419,213.7,4788,299.2,444,27.8,2256,141.0,3832,239.5,6088,380.5
15,Kansas City ChiefsKansas City,211,13.2,2395,149.7,2713,169.6,5108,319.2,425,26.6,2171,135.7,3533,220.8,5704,356.5
16,Miami DolphinsMiami,288,18.0,1802,112.6,3182,198.9,4984,311.5,317,19.8,1734,108.4,3974,248.4,5708,356.8
17,Minnesota VikingsMinnesota,379,23.7,2634,164.6,2751,171.9,5385,336.6,348,21.8,1692,105.8,3908,244.2,5600,350.0
18,New England PatriotsNew England,557,34.8,2184,136.5,4662,291.4,6846,427.9,331,20.7,1630,101.9,4342,271.4,5972,373.2
19,New Orleans SaintsNew Orleans,461,28.8,1577,98.6,4997,312.3,6574,410.9,454,28.4,2361,147.6,4681,292.6,7042,440.1
20,New York GiantsNY Giants,429,26.8,1862,116.4,3825,239.1,5687,355.4,344,21.5,2066,129.1,4068,254.2,6134,383.4
21,New York JetsNY Jets,281,17.6,1896,118.5,2891,180.7,4787,299.2,375,23.4,2138,133.6,3036,189.8,5174,323.4
22,Oakland RaidersOakland,290,18.1,1420,88.8,4084,255.2,5504,344.0,443,27.7,1897,118.6,3775,235.9,5672,354.5
23,Philadelphia EaglesPhiladelphia,280,17.5,1874,117.1,3791,236.9,5665,354.1,444,27.8,2021,126.3,3470,216.9,5491,343.2
24,Pittsburgh SteelersPittsburgh,336,21.0,1537,96.1,3787,236.7,5324,332.8,314,19.6,1450,90.6,2963,185.2,4413,275.8
25,San Diego ChargersSan Diego,350,21.9,1461,91.3,3295,205.9,4756,297.2,350,21.9,1542,96.4,3681,230.1,5223,326.4
26,San Francisco 49ersSan Francisco,397,24.8,2491,155.7,3298,206.1,5789,361.8,273,17.1,1507,94.2,3203,200.2,4710,294.4
27,Seattle SeahawksSeattle,412,25.8,2579,161.2,3031,189.4,5610,350.6,245,15.3,1649,103.1,3250,203.1,4899,306.2
28,St. Louis RamsSt. Louis,299,18.7,1714,107.1,3550,221.9,5264,329.0,348,21.8,1880,117.5,3602,225.1,5482,342.6
29,Tampa Bay BuccaneersTampa Bay,389,24.3,1837,114.8,3983,248.9,5820,363.8,394,24.6,1320,82.5,4758,297.4,6078,379.9
30,Tennessee TitansTennessee,330,20.6,1687,105.4,3323,207.7,5010,313.1,471,29.4,2035,127.2,3964,247.8,5999,374.9
31,Washington RedskinsWashington,436,27.2,2709,169.3,3422,213.9,6131,383.2,388,24.2,1532,95.8,4511,281.9,6043,377.7

### Rename the Teams in off/def to match incoming data

In [32]:
teamnames = {'Arizona CardinalsArizona': 'Arizona Cardinals', 'Atlanta FalconsAtlanta': 'Atlanta Falcons', 
             'Baltimore RavensBaltimore': 'Baltimore Ravens', 'Buffalo BillsBuffalo': 'Buffalo Bills',
            'Carolina PanthersCarolina': 'Carolina Panthers', 'Chicago BearsChicago': 'Chicago Bears',
            'Cincinnati BengalsCincinnati': 'Cincinnati Bengals', 'Cleveland BrownsCleveland': 'Cleveland Browns',
            'Dallas CowboysDallas': 'Dallas Cowboys', 'Denver BroncosDenver': 'Denver Broncos', 
             'Detroit LionsDetroit': 'Detroit Lions', 'Green Bay PackersGreen Bay': 'Green Bay Packers',
            'Houston TexansHouston': 'Houston Texans', 'Indianapolis ColtsIndianapolis': 'Indianapolis Colts',
            'Jacksonville JaguarsJacksonville': 'Jacksonville Jaguars', 'Kansas City ChiefsKansas City': 'Kansas City Chiefs',
            'Miami DolphinsMiami': 'Miami Dolphins', 'Minnesota VikingsMinnesota': 'Minnesota Vikings', 
            'New England PatriotsNew England': 'New England Patriots', 'New Orleans SaintsNew Orleans': 'New Orleans Saints',
            'New York GiantsNY Giants': 'New York Giants', 'New York JetsNY Jets': 'New York Jets', 
            'Oakland RaidersOakland': 'Las Vegas Raiders', 'Philadelphia EaglesPhiladelphia': 'Philadelphia Eagles',
            'Pittsburgh SteelersPittsburgh': 'Pittsburgh Steelers', 'San Diego ChargersSan Diego': 'Los Angeles Chargers',
            'San Francisco 49ersSan Francisco': 'San Francisco 49ers', 'Seattle SeahawksSeattle': 'Seattle Seahawks',
            'St. Louis RamsSt. Louis': 'Los Angeles Rams', 
            'Tampa Bay BuccaneersTampa Bay': 'Tampa Bay Buccaneers', 'Tennessee TitansTennessee': 'Tennessee Titans',
            'Washington RedskinsWashington': 'Washington Commanders'}
off_def2012['Team'] = off_def2012['Team'].replace(teamnames)

In [33]:
off_def2012.head(32)

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,22.3,2192,137.0,3213,200.8,5405,337.8
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,18.7,1971,123.2,3878,242.4,5849,365.6
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,21.5,1965,122.8,3650,228.1,5615,350.9
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,27.2,2333,145.8,3473,217.1,5806,362.9
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,22.7,1761,110.1,3568,223.0,5329,333.1
5,Chicago Bears,375,23.4,1970,123.1,2999,187.4,4969,310.6,277,17.3,1627,101.7,3423,213.9,5050,315.6
6,Cincinnati Bengals,391,24.4,1745,109.1,3578,223.6,5323,332.7,320,20.0,1715,107.2,3400,212.5,5115,319.7
7,Cleveland Browns,302,18.9,1593,99.6,3435,214.7,5028,314.2,368,23.0,1898,118.6,3923,245.2,5821,363.8
8,Dallas Cowboys,376,23.5,1265,79.1,4729,295.6,5994,374.6,400,25.0,2003,125.2,3684,230.2,5687,355.4
9,Denver Broncos,481,30.1,1832,114.5,4534,283.4,6366,397.9,289,18.1,1458,91.1,3194,199.6,4652,290.8
10,Detroit Lions,372,23.2,1613,100.8,4927,307.9,6540,408.8,437,27.3,1889,118.1,3569,223.1,5458,341.1
11,Green Bay Packers,433,27.1,1702,106.4,4049,253.1,5751,359.4,336,21.0,1896,118.5,3492,218.2,5388,336.8
12,Houston Texans,416,26.0,2123,132.7,3830,239.4,5953,372.1,331,20.7,1560,97.5,3612,225.8,5172,323.2
13,Indianapolis Colts,357,22.3,1671,104.4,4128,258.0,5799,362.4,387,24.2,2200,137.5,3788,236.8,5988,374.2
14,Jacksonville Jaguars,255,15.9,1369,85.6,3419,213.7,4788,299.2,444,27.8,2256,141.0,3832,239.5,6088,380.5
15,Kansas City Chiefs,211,13.2,2395,149.7,2713,169.6,5108,319.2,425,26.6,2171,135.7,3533,220.8,5704,356.5
16,Miami Dolphins,288,18.0,1802,112.6,3182,198.9,4984,311.5,317,19.8,1734,108.4,3974,248.4,5708,356.8
17,Minnesota Vikings,379,23.7,2634,164.6,2751,171.9,5385,336.6,348,21.8,1692,105.8,3908,244.2,5600,350.0
18,New England Patriots,557,34.8,2184,136.5,4662,291.4,6846,427.9,331,20.7,1630,101.9,4342,271.4,5972,373.2
19,New Orleans Saints,461,28.8,1577,98.6,4997,312.3,6574,410.9,454,28.4,2361,147.6,4681,292.6,7042,440.1
20,New York Giants,429,26.8,1862,116.4,3825,239.1,5687,355.4,344,21.5,2066,129.1,4068,254.2,6134,383.4
21,New York Jets,281,17.6,1896,118.5,2891,180.7,4787,299.2,375,23.4,2138,133.6,3036,189.8,5174,323.4
22,Las Vegas Raiders,290,18.1,1420,88.8,4084,255.2,5504,344.0,443,27.7,1897,118.6,3775,235.9,5672,354.5
23,Philadelphia Eagles,280,17.5,1874,117.1,3791,236.9,5665,354.1,444,27.8,2021,126.3,3470,216.9,5491,343.2
24,Pittsburgh Steelers,336,21.0,1537,96.1,3787,236.7,5324,332.8,314,19.6,1450,90.6,2963,185.2,4413,275.8
25,Los Angeles Chargers,350,21.9,1461,91.3,3295,205.9,4756,297.2,350,21.9,1542,96.4,3681,230.1,5223,326.4
26,San Francisco 49ers,397,24.8,2491,155.7,3298,206.1,5789,361.8,273,17.1,1507,94.2,3203,200.2,4710,294.4
27,Seattle Seahawks,412,25.8,2579,161.2,3031,189.4,5610,350.6,245,15.3,1649,103.1,3250,203.1,4899,306.2
28,Los Angeles Rams,299,18.7,1714,107.1,3550,221.9,5264,329.0,348,21.8,1880,117.5,3602,225.1,5482,342.6
29,Tampa Bay Buccaneers,389,24.3,1837,114.8,3983,248.9,5820,363.8,394,24.6,1320,82.5,4758,297.4,6078,379.9
30,Tennessee Titans,330,20.6,1687,105.4,3323,207.7,5010,313.1,471,29.4,2035,127.2,3964,247.8,5999,374.9
31,Washington Commanders,436,27.2,2709,169.3,3422,213.9,6131,383.2,388,24.2,1532,95.8,4511,281.9,6043,377.7

### Put Dataset in Team Ascending Order

In [34]:
off_def2012 = off_def2012.sort_values("Team")

In [35]:
off_def2012.head(32)

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G,2012 Def Tot Pts,2012 Def Pts/G,2012 Def RushYds,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,22.3,2192,137.0,3213,200.8,5405,337.8
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,18.7,1971,123.2,3878,242.4,5849,365.6
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,21.5,1965,122.8,3650,228.1,5615,350.9
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,27.2,2333,145.8,3473,217.1,5806,362.9
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,22.7,1761,110.1,3568,223.0,5329,333.1
5,Chicago Bears,375,23.4,1970,123.1,2999,187.4,4969,310.6,277,17.3,1627,101.7,3423,213.9,5050,315.6
6,Cincinnati Bengals,391,24.4,1745,109.1,3578,223.6,5323,332.7,320,20.0,1715,107.2,3400,212.5,5115,319.7
7,Cleveland Browns,302,18.9,1593,99.6,3435,214.7,5028,314.2,368,23.0,1898,118.6,3923,245.2,5821,363.8
8,Dallas Cowboys,376,23.5,1265,79.1,4729,295.6,5994,374.6,400,25.0,2003,125.2,3684,230.2,5687,355.4
9,Denver Broncos,481,30.1,1832,114.5,4534,283.4,6366,397.9,289,18.1,1458,91.1,3194,199.6,4652,290.8
10,Detroit Lions,372,23.2,1613,100.8,4927,307.9,6540,408.8,437,27.3,1889,118.1,3569,223.1,5458,341.1
11,Green Bay Packers,433,27.1,1702,106.4,4049,253.1,5751,359.4,336,21.0,1896,118.5,3492,218.2,5388,336.8
12,Houston Texans,416,26.0,2123,132.7,3830,239.4,5953,372.1,331,20.7,1560,97.5,3612,225.8,5172,323.2
13,Indianapolis Colts,357,22.3,1671,104.4,4128,258.0,5799,362.4,387,24.2,2200,137.5,3788,236.8,5988,374.2
14,Jacksonville Jaguars,255,15.9,1369,85.6,3419,213.7,4788,299.2,444,27.8,2256,141.0,3832,239.5,6088,380.5
15,Kansas City Chiefs,211,13.2,2395,149.7,2713,169.6,5108,319.2,425,26.6,2171,135.7,3533,220.8,5704,356.5
22,Las Vegas Raiders,290,18.1,1420,88.8,4084,255.2,5504,344.0,443,27.7,1897,118.6,3775,235.9,5672,354.5
25,Los Angeles Chargers,350,21.9,1461,91.3,3295,205.9,4756,297.2,350,21.9,1542,96.4,3681,230.1,5223,326.4
28,Los Angeles Rams,299,18.7,1714,107.1,3550,221.9,5264,329.0,348,21.8,1880,117.5,3602,225.1,5482,342.6
16,Miami Dolphins,288,18.0,1802,112.6,3182,198.9,4984,311.5,317,19.8,1734,108.4,3974,248.4,5708,356.8
17,Minnesota Vikings,379,23.7,2634,164.6,2751,171.9,5385,336.6,348,21.8,1692,105.8,3908,244.2,5600,350.0
18,New England Patriots,557,34.8,2184,136.5,4662,291.4,6846,427.9,331,20.7,1630,101.9,4342,271.4,5972,373.2
19,New Orleans Saints,461,28.8,1577,98.6,4997,312.3,6574,410.9,454,28.4,2361,147.6,4681,292.6,7042,440.1
20,New York Giants,429,26.8,1862,116.4,3825,239.1,5687,355.4,344,21.5,2066,129.1,4068,254.2,6134,383.4
21,New York Jets,281,17.6,1896,118.5,2891,180.7,4787,299.2,375,23.4,2138,133.6,3036,189.8,5174,323.4
23,Philadelphia Eagles,280,17.5,1874,117.1,3791,236.9,5665,354.1,444,27.8,2021,126.3,3470,216.9,5491,343.2
24,Pittsburgh Steelers,336,21.0,1537,96.1,3787,236.7,5324,332.8,314,19.6,1450,90.6,2963,185.2,4413,275.8
26,San Francisco 49ers,397,24.8,2491,155.7,3298,206.1,5789,361.8,273,17.1,1507,94.2,3203,200.2,4710,294.4
27,Seattle Seahawks,412,25.8,2579,161.2,3031,189.4,5610,350.6,245,15.3,1649,103.1,3250,203.1,4899,306.2
29,Tampa Bay Buccaneers,389,24.3,1837,114.8,3983,248.9,5820,363.8,394,24.6,1320,82.5,4758,297.4,6078,379.9
30,Tennessee Titans,330,20.6,1687,105.4,3323,207.7,5010,313.1,471,29.4,2035,127.2,3964,247.8,5999,374.9
31,Washington Commanders,436,27.2,2709,169.3,3422,213.9,6131,383.2,388,24.2,1532,95.8,4511,281.9,6043,377.7

### Merge dataset with off/def data

In [36]:
nfl2012complete = pd.merge(off_def2012, wl2012, on='Team')

In [37]:
nfl2012complete.head()

,Team,2012 Off Tot Pts,2012 Off Pts/G,2012 Off RushYds,2012 Off RYds/G,2012 Off PassYds,2012 Off PYds/G,2012 Off TotYds,2012 Off Yds/G,2012 Def Tot Pts,...,2012 Def RYds/G,2012 Def PassYds,2012 Def PYds/G,2012 Def TotYds,2012 Def Yds/G,2012 Wins,2012 Loss,2012 Tie,2012 Superbowl,2012 SB Win
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,...,137.0,3213,200.8,5405,337.8,5,11,0,No,No
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,...,123.2,3878,242.4,5849,365.6,13,3,0,No,No
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,...,122.8,3650,228.1,5615,350.9,10,6,0,Yes,Yes
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,...,145.8,3473,217.1,5806,362.9,6,10,0,No,No
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,...,110.1,3568,223.0,5329,333.1,7,9,0,No,No

### Save Data for future use

In [67]:
nfl2012complete.to_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2012complete.csv')

## Import 2013 Offense & Defense Datasets

In [38]:
off2013 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2013_offense.csv')

In [39]:
def2013 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2013_defense.csv')

In [40]:
off2013.head()

,Unnamed: 0,Team,2013 Off Tot Pts,2013 Off Pts/G,2013 Off RushYds,2013 Off RYds/G,2013 Off PassYds,2013 Off PYds/G,2013 Off TotYds,2013 Off Yds/G
0,11,Arizona CardinalsArizona,379,23.7,1540,96.2,4002,250.1,5542,346.4
1,13,Atlanta FalconsAtlanta,353,22.1,1247,77.9,4243,265.2,5490,343.1
2,28,Baltimore RavensBaltimore,320,20.0,1328,83.0,3590,224.4,4918,307.4
3,18,Buffalo BillsBuffalo,339,21.2,2307,144.2,3103,193.9,5410,338.1
4,25,Carolina PanthersCarolina,366,22.9,2026,126.6,3043,190.2,5069,316.8

In [41]:
def2013.head()

,Unnamed: 0,Team,2013 Def Tot Pts,2013 Def Pts/G,2013 Def RushYds,2013 Def RYds/G,2013 Def PassYds,2013 Def PYds/G,2013 Def TotYds,2013 Def Yds/G
0,5,Arizona CardinalsArizona,324,20.2,1351,84.4,3728,233.0,5079,317.4
1,26,Atlanta FalconsAtlanta,443,27.7,2173,135.8,3897,243.6,6070,379.4
2,11,Baltimore RavensBaltimore,352,22.0,1687,105.4,3681,230.1,5368,335.5
3,9,Buffalo BillsBuffalo,388,24.2,2063,128.9,3271,204.4,5334,333.4
4,1,Carolina PanthersCarolina,241,15.1,1391,86.9,3429,214.3,4820,301.2

### Drop unnamed column in both datasets

In [42]:
off2013 = off2013.iloc[:, 1:]

In [43]:
off2013.head()

,Team,2013 Off Tot Pts,2013 Off Pts/G,2013 Off RushYds,2013 Off RYds/G,2013 Off PassYds,2013 Off PYds/G,2013 Off TotYds,2013 Off Yds/G
0,Arizona CardinalsArizona,379,23.7,1540,96.2,4002,250.1,5542,346.4
1,Atlanta FalconsAtlanta,353,22.1,1247,77.9,4243,265.2,5490,343.1
2,Baltimore RavensBaltimore,320,20.0,1328,83.0,3590,224.4,4918,307.4
3,Buffalo BillsBuffalo,339,21.2,2307,144.2,3103,193.9,5410,338.1
4,Carolina PanthersCarolina,366,22.9,2026,126.6,3043,190.2,5069,316.8

In [45]:
def2013 = def2013.iloc[:, 1:]

In [46]:
def2013.head()

,Team,2013 Def Tot Pts,2013 Def Pts/G,2013 Def RushYds,2013 Def RYds/G,2013 Def PassYds,2013 Def PYds/G,2013 Def TotYds,2013 Def Yds/G
0,Arizona CardinalsArizona,324,20.2,1351,84.4,3728,233.0,5079,317.4
1,Atlanta FalconsAtlanta,443,27.7,2173,135.8,3897,243.6,6070,379.4
2,Baltimore RavensBaltimore,352,22.0,1687,105.4,3681,230.1,5368,335.5
3,Buffalo BillsBuffalo,388,24.2,2063,128.9,3271,204.4,5334,333.4
4,Carolina PanthersCarolina,241,15.1,1391,86.9,3429,214.3,4820,301.2

### Merge 2013 Offense & Defense Data

In [47]:
off_def2013 = pd.merge(off2013, def2013)

In [49]:
off_def2013.head(32)

,Team,2013 Off Tot Pts,2013 Off Pts/G,2013 Off RushYds,2013 Off RYds/G,2013 Off PassYds,2013 Off PYds/G,2013 Off TotYds,2013 Off Yds/G,2013 Def Tot Pts,2013 Def Pts/G,2013 Def RushYds,2013 Def RYds/G,2013 Def PassYds,2013 Def PYds/G,2013 Def TotYds,2013 Def Yds/G
0,Arizona CardinalsArizona,379,23.7,1540,96.2,4002,250.1,5542,346.4,324,20.2,1351,84.4,3728,233.0,5079,317.4
1,Atlanta FalconsAtlanta,353,22.1,1247,77.9,4243,265.2,5490,343.1,443,27.7,2173,135.8,3897,243.6,6070,379.4
2,Baltimore RavensBaltimore,320,20.0,1328,83.0,3590,224.4,4918,307.4,352,22.0,1687,105.4,3681,230.1,5368,335.5
3,Buffalo BillsBuffalo,339,21.2,2307,144.2,3103,193.9,5410,338.1,388,24.2,2063,128.9,3271,204.4,5334,333.4
4,Carolina PanthersCarolina,366,22.9,2026,126.6,3043,190.2,5069,316.8,241,15.1,1391,86.9,3429,214.3,4820,301.2
5,Chicago BearsChicago,445,27.8,1828,114.2,4281,267.6,6109,381.8,478,29.9,2583,161.4,3730,233.1,6313,394.6
6,Cincinnati BengalsCincinnati,430,26.9,1755,109.7,4136,258.5,5891,368.2,305,19.1,1544,96.5,3344,209.0,4888,305.5
7,Cleveland BrownsCleveland,308,19.2,1383,86.4,4047,252.9,5430,339.4,406,25.4,1781,111.3,3538,221.1,5319,332.4
8,Dallas CowboysDallas,439,27.4,1504,94.0,3954,247.1,5458,341.1,432,27.0,2056,128.5,4589,286.8,6645,415.3
9,Denver BroncosDenver,606,37.9,1873,117.1,5444,340.2,7317,457.3,399,24.9,1626,101.6,4070,254.4,5696,356.0
10,Detroit LionsDetroit,395,24.7,1792,112.0,4482,280.1,6274,392.1,376,23.5,1596,99.8,3950,246.9,5546,346.6
11,Green Bay PackersGreen Bay,417,26.1,2136,133.5,4268,266.8,6404,400.2,428,26.8,2000,125.0,3956,247.2,5956,372.2
12,Houston TexansHouston,276,17.2,1743,108.9,3813,238.3,5556,347.2,428,26.8,1958,122.4,3123,195.2,5081,317.6
13,Indianapolis ColtsIndianapolis,391,24.4,1743,108.9,3725,232.8,5468,341.8,336,21.0,2002,125.1,3711,231.9,5713,357.1
14,Jacksonville JaguarsJacksonville,247,15.4,1260,78.8,3441,215.1,4701,293.8,449,28.1,2108,131.8,3962,247.6,6070,379.4
15,Kansas City ChiefsKansas City,430,26.9,2056,128.5,3340,208.8,5396,337.2,305,19.1,1923,120.2,3962,247.6,5885,367.8
16,Miami DolphinsMiami,317,19.8,1440,90.0,3567,222.9,5007,312.9,335,20.9,1998,124.9,3752,234.5,5750,359.4
17,Minnesota VikingsMinnesota,391,24.4,2081,130.1,3427,214.2,5508,344.2,480,30.0,1767,110.4,4595,287.2,6362,397.6
18,New England PatriotsNew England,444,27.8,2065,129.1,4087,255.4,6152,384.5,338,21.1,2145,134.1,3824,239.0,5969,373.1
19,New Orleans SaintsNew Orleans,414,25.9,1473,92.1,4918,307.4,6391,399.4,304,19.0,1786,111.6,3105,194.1,4891,305.7
20,New York GiantsNY Giants,294,18.4,1332,83.2,3588,224.2,4920,307.5,383,23.9,1743,108.9,3573,223.3,5316,332.2
21,New York JetsNY Jets,290,18.1,2158,134.9,2932,183.2,5090,318.1,387,24.2,1412,88.2,3947,246.7,5359,334.9
22,Oakland RaidersOakland,322,20.1,2000,125.0,3340,208.8,5340,333.8,453,28.3,1727,107.9,4092,255.8,5819,363.7
23,Philadelphia EaglesPhiladelphia,442,27.6,2566,160.4,4110,256.9,6676,417.2,382,23.9,1668,104.2,4636,289.8,6304,394.0
24,Pittsburgh SteelersPittsburgh,379,23.7,1383,86.4,4017,251.1,5400,337.5,370,23.1,1849,115.6,3553,222.1,5402,337.6
25,San Diego ChargersSan Diego,396,24.8,1965,122.8,4328,270.5,6293,393.3,348,21.8,1725,107.8,4139,258.7,5864,366.5
26,San Francisco 49ersSan Francisco,406,25.4,2201,137.6,2979,186.2,5180,323.8,272,17.0,1535,95.9,3536,221.0,5071,316.9
27,Seattle SeahawksSeattle,417,26.1,2188,136.8,3236,202.2,5424,339.0,231,14.4,1626,101.6,2752,172.0,4378,273.6
28,St. Louis RamsSt. Louis,348,21.8,1752,109.5,3125,195.3,4877,304.8,364,22.8,1646,102.9,3874,242.1,5520,345.0
29,Tampa Bay BuccaneersTampa Bay,288,18.0,1612,100.8,2820,176.2,4432,277.0,389,24.3,1762,110.1,3806,237.9,5568,348.0
30,Tennessee TitansTennessee,362,22.6,1894,118.4,3496,218.5,5390,336.9,381,23.8,1795,112.2,3612,225.8,5407,337.9
31,Washington RedskinsWashington,334,20.9,2164,135.2,3751,234.4,5915,369.7,478,29.9,1769,110.6,3896,243.5,5665,354.1

### Rename Teams to match incoming data

In [50]:
teamnames13 = {'Arizona CardinalsArizona': 'Arizona Cardinals', 'Atlanta FalconsAtlanta': 'Atlanta Falcons', 
             'Baltimore RavensBaltimore': 'Baltimore Ravens', 'Buffalo BillsBuffalo': 'Buffalo Bills',
            'Carolina PanthersCarolina': 'Carolina Panthers', 'Chicago BearsChicago': 'Chicago Bears',
            'Cincinnati BengalsCincinnati': 'Cincinnati Bengals', 'Cleveland BrownsCleveland': 'Cleveland Browns',
            'Dallas CowboysDallas': 'Dallas Cowboys', 'Denver BroncosDenver': 'Denver Broncos', 
             'Detroit LionsDetroit': 'Detroit Lions', 'Green Bay PackersGreen Bay': 'Green Bay Packers',
            'Houston TexansHouston': 'Houston Texans', 'Indianapolis ColtsIndianapolis': 'Indianapolis Colts',
            'Jacksonville JaguarsJacksonville': 'Jacksonville Jaguars', 'Kansas City ChiefsKansas City': 'Kansas City Chiefs',
            'Miami DolphinsMiami': 'Miami Dolphins', 'Minnesota VikingsMinnesota': 'Minnesota Vikings', 
            'New England PatriotsNew England': 'New England Patriots', 'New Orleans SaintsNew Orleans': 'New Orleans Saints',
            'New York GiantsNY Giants': 'New York Giants', 'New York JetsNY Jets': 'New York Jets', 
            'Oakland RaidersOakland': 'Las Vegas Raiders', 'Philadelphia EaglesPhiladelphia': 'Philadelphia Eagles',
            'Pittsburgh SteelersPittsburgh': 'Pittsburgh Steelers', 'San Diego ChargersSan Diego': 'Los Angeles Chargers',
            'San Francisco 49ersSan Francisco': 'San Francisco 49ers', 'Seattle SeahawksSeattle': 'Seattle Seahawks',
            'St. Louis RamsSt. Louis': 'Los Angeles Rams', 
            'Tampa Bay BuccaneersTampa Bay': 'Tampa Bay Buccaneers', 'Tennessee TitansTennessee': 'Tennessee Titans',
            'Washington RedskinsWashington': 'Washington Commanders'}
off_def2013['Team'] = off_def2013['Team'].replace(teamnames13)

In [51]:
off_def2013.head(32)

,Team,2013 Off Tot Pts,2013 Off Pts/G,2013 Off RushYds,2013 Off RYds/G,2013 Off PassYds,2013 Off PYds/G,2013 Off TotYds,2013 Off Yds/G,2013 Def Tot Pts,2013 Def Pts/G,2013 Def RushYds,2013 Def RYds/G,2013 Def PassYds,2013 Def PYds/G,2013 Def TotYds,2013 Def Yds/G
0,Arizona Cardinals,379,23.7,1540,96.2,4002,250.1,5542,346.4,324,20.2,1351,84.4,3728,233.0,5079,317.4
1,Atlanta Falcons,353,22.1,1247,77.9,4243,265.2,5490,343.1,443,27.7,2173,135.8,3897,243.6,6070,379.4
2,Baltimore Ravens,320,20.0,1328,83.0,3590,224.4,4918,307.4,352,22.0,1687,105.4,3681,230.1,5368,335.5
3,Buffalo Bills,339,21.2,2307,144.2,3103,193.9,5410,338.1,388,24.2,2063,128.9,3271,204.4,5334,333.4
4,Carolina Panthers,366,22.9,2026,126.6,3043,190.2,5069,316.8,241,15.1,1391,86.9,3429,214.3,4820,301.2
5,Chicago Bears,445,27.8,1828,114.2,4281,267.6,6109,381.8,478,29.9,2583,161.4,3730,233.1,6313,394.6
6,Cincinnati Bengals,430,26.9,1755,109.7,4136,258.5,5891,368.2,305,19.1,1544,96.5,3344,209.0,4888,305.5
7,Cleveland Browns,308,19.2,1383,86.4,4047,252.9,5430,339.4,406,25.4,1781,111.3,3538,221.1,5319,332.4
8,Dallas Cowboys,439,27.4,1504,94.0,3954,247.1,5458,341.1,432,27.0,2056,128.5,4589,286.8,6645,415.3
9,Denver Broncos,606,37.9,1873,117.1,5444,340.2,7317,457.3,399,24.9,1626,101.6,4070,254.4,5696,356.0
10,Detroit Lions,395,24.7,1792,112.0,4482,280.1,6274,392.1,376,23.5,1596,99.8,3950,246.9,5546,346.6
11,Green Bay Packers,417,26.1,2136,133.5,4268,266.8,6404,400.2,428,26.8,2000,125.0,3956,247.2,5956,372.2
12,Houston Texans,276,17.2,1743,108.9,3813,238.3,5556,347.2,428,26.8,1958,122.4,3123,195.2,5081,317.6
13,Indianapolis Colts,391,24.4,1743,108.9,3725,232.8,5468,341.8,336,21.0,2002,125.1,3711,231.9,5713,357.1
14,Jacksonville Jaguars,247,15.4,1260,78.8,3441,215.1,4701,293.8,449,28.1,2108,131.8,3962,247.6,6070,379.4
15,Kansas City Chiefs,430,26.9,2056,128.5,3340,208.8,5396,337.2,305,19.1,1923,120.2,3962,247.6,5885,367.8
16,Miami Dolphins,317,19.8,1440,90.0,3567,222.9,5007,312.9,335,20.9,1998,124.9,3752,234.5,5750,359.4
17,Minnesota Vikings,391,24.4,2081,130.1,3427,214.2,5508,344.2,480,30.0,1767,110.4,4595,287.2,6362,397.6
18,New England Patriots,444,27.8,2065,129.1,4087,255.4,6152,384.5,338,21.1,2145,134.1,3824,239.0,5969,373.1
19,New Orleans Saints,414,25.9,1473,92.1,4918,307.4,6391,399.4,304,19.0,1786,111.6,3105,194.1,4891,305.7
20,New York Giants,294,18.4,1332,83.2,3588,224.2,4920,307.5,383,23.9,1743,108.9,3573,223.3,5316,332.2
21,New York Jets,290,18.1,2158,134.9,2932,183.2,5090,318.1,387,24.2,1412,88.2,3947,246.7,5359,334.9
22,Las Vegas Raiders,322,20.1,2000,125.0,3340,208.8,5340,333.8,453,28.3,1727,107.9,4092,255.8,5819,363.7
23,Philadelphia Eagles,442,27.6,2566,160.4,4110,256.9,6676,417.2,382,23.9,1668,104.2,4636,289.8,6304,394.0
24,Pittsburgh Steelers,379,23.7,1383,86.4,4017,251.1,5400,337.5,370,23.1,1849,115.6,3553,222.1,5402,337.6
25,Los Angeles Chargers,396,24.8,1965,122.8,4328,270.5,6293,393.3,348,21.8,1725,107.8,4139,258.7,5864,366.5
26,San Francisco 49ers,406,25.4,2201,137.6,2979,186.2,5180,323.8,272,17.0,1535,95.9,3536,221.0,5071,316.9
27,Seattle Seahawks,417,26.1,2188,136.8,3236,202.2,5424,339.0,231,14.4,1626,101.6,2752,172.0,4378,273.6
28,Los Angeles Rams,348,21.8,1752,109.5,3125,195.3,4877,304.8,364,22.8,1646,102.9,3874,242.1,5520,345.0
29,Tampa Bay Buccaneers,288,18.0,1612,100.8,2820,176.2,4432,277.0,389,24.3,1762,110.1,3806,237.9,5568,348.0
30,Tennessee Titans,362,22.6,1894,118.4,3496,218.5,5390,336.9,381,23.8,1795,112.2,3612,225.8,5407,337.9
31,Washington Commanders,334,20.9,2164,135.2,3751,234.4,5915,369.7,478,29.9,1769,110.6,3896,243.5,5665,354.1

### Put Dataset in Team Ascending Order

In [52]:
off_def2013 = off_def2013.sort_values("Team")

In [53]:
off_def2013.head(32)

,Team,2013 Off Tot Pts,2013 Off Pts/G,2013 Off RushYds,2013 Off RYds/G,2013 Off PassYds,2013 Off PYds/G,2013 Off TotYds,2013 Off Yds/G,2013 Def Tot Pts,2013 Def Pts/G,2013 Def RushYds,2013 Def RYds/G,2013 Def PassYds,2013 Def PYds/G,2013 Def TotYds,2013 Def Yds/G
0,Arizona Cardinals,379,23.7,1540,96.2,4002,250.1,5542,346.4,324,20.2,1351,84.4,3728,233.0,5079,317.4
1,Atlanta Falcons,353,22.1,1247,77.9,4243,265.2,5490,343.1,443,27.7,2173,135.8,3897,243.6,6070,379.4
2,Baltimore Ravens,320,20.0,1328,83.0,3590,224.4,4918,307.4,352,22.0,1687,105.4,3681,230.1,5368,335.5
3,Buffalo Bills,339,21.2,2307,144.2,3103,193.9,5410,338.1,388,24.2,2063,128.9,3271,204.4,5334,333.4
4,Carolina Panthers,366,22.9,2026,126.6,3043,190.2,5069,316.8,241,15.1,1391,86.9,3429,214.3,4820,301.2
5,Chicago Bears,445,27.8,1828,114.2,4281,267.6,6109,381.8,478,29.9,2583,161.4,3730,233.1,6313,394.6
6,Cincinnati Bengals,430,26.9,1755,109.7,4136,258.5,5891,368.2,305,19.1,1544,96.5,3344,209.0,4888,305.5
7,Cleveland Browns,308,19.2,1383,86.4,4047,252.9,5430,339.4,406,25.4,1781,111.3,3538,221.1,5319,332.4
8,Dallas Cowboys,439,27.4,1504,94.0,3954,247.1,5458,341.1,432,27.0,2056,128.5,4589,286.8,6645,415.3
9,Denver Broncos,606,37.9,1873,117.1,5444,340.2,7317,457.3,399,24.9,1626,101.6,4070,254.4,5696,356.0
10,Detroit Lions,395,24.7,1792,112.0,4482,280.1,6274,392.1,376,23.5,1596,99.8,3950,246.9,5546,346.6
11,Green Bay Packers,417,26.1,2136,133.5,4268,266.8,6404,400.2,428,26.8,2000,125.0,3956,247.2,5956,372.2
12,Houston Texans,276,17.2,1743,108.9,3813,238.3,5556,347.2,428,26.8,1958,122.4,3123,195.2,5081,317.6
13,Indianapolis Colts,391,24.4,1743,108.9,3725,232.8,5468,341.8,336,21.0,2002,125.1,3711,231.9,5713,357.1
14,Jacksonville Jaguars,247,15.4,1260,78.8,3441,215.1,4701,293.8,449,28.1,2108,131.8,3962,247.6,6070,379.4
15,Kansas City Chiefs,430,26.9,2056,128.5,3340,208.8,5396,337.2,305,19.1,1923,120.2,3962,247.6,5885,367.8
22,Las Vegas Raiders,322,20.1,2000,125.0,3340,208.8,5340,333.8,453,28.3,1727,107.9,4092,255.8,5819,363.7
25,Los Angeles Chargers,396,24.8,1965,122.8,4328,270.5,6293,393.3,348,21.8,1725,107.8,4139,258.7,5864,366.5
28,Los Angeles Rams,348,21.8,1752,109.5,3125,195.3,4877,304.8,364,22.8,1646,102.9,3874,242.1,5520,345.0
16,Miami Dolphins,317,19.8,1440,90.0,3567,222.9,5007,312.9,335,20.9,1998,124.9,3752,234.5,5750,359.4
17,Minnesota Vikings,391,24.4,2081,130.1,3427,214.2,5508,344.2,480,30.0,1767,110.4,4595,287.2,6362,397.6
18,New England Patriots,444,27.8,2065,129.1,4087,255.4,6152,384.5,338,21.1,2145,134.1,3824,239.0,5969,373.1
19,New Orleans Saints,414,25.9,1473,92.1,4918,307.4,6391,399.4,304,19.0,1786,111.6,3105,194.1,4891,305.7
20,New York Giants,294,18.4,1332,83.2,3588,224.2,4920,307.5,383,23.9,1743,108.9,3573,223.3,5316,332.2
21,New York Jets,290,18.1,2158,134.9,2932,183.2,5090,318.1,387,24.2,1412,88.2,3947,246.7,5359,334.9
23,Philadelphia Eagles,442,27.6,2566,160.4,4110,256.9,6676,417.2,382,23.9,1668,104.2,4636,289.8,6304,394.0
24,Pittsburgh Steelers,379,23.7,1383,86.4,4017,251.1,5400,337.5,370,23.1,1849,115.6,3553,222.1,5402,337.6
26,San Francisco 49ers,406,25.4,2201,137.6,2979,186.2,5180,323.8,272,17.0,1535,95.9,3536,221.0,5071,316.9
27,Seattle Seahawks,417,26.1,2188,136.8,3236,202.2,5424,339.0,231,14.4,1626,101.6,2752,172.0,4378,273.6
29,Tampa Bay Buccaneers,288,18.0,1612,100.8,2820,176.2,4432,277.0,389,24.3,1762,110.1,3806,237.9,5568,348.0
30,Tennessee Titans,362,22.6,1894,118.4,3496,218.5,5390,336.9,381,23.8,1795,112.2,3612,225.8,5407,337.9
31,Washington Commanders,334,20.9,2164,135.2,3751,234.4,5915,369.7,478,29.9,1769,110.6,3896,243.5,5665,354.1

### Import 2013 Win/Loss Datset

In [60]:
wl2013 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_win_lose/NFL_2013_wl.csv')

In [61]:
wl2013.head()

,Unnamed: 0,Team,2013 Wins,2013 Loss,2013 Tie,2013 Superbowl,2013 SB Win
0,21,Arizona Cardinals,10,6,0,No,No
1,2,Atlanta Falcons,4,12,0,No,No
2,13,Baltimore Ravens,8,8,0,No,No
3,8,Buffalo Bills,6,10,0,No,No
4,27,Carolina Panthers,12,4,0,No,No

### Drop Unnamed Column

In [62]:
wl2013 = wl2013.iloc[:, 1:]

In [63]:
wl2013.head()

,Team,2013 Wins,2013 Loss,2013 Tie,2013 Superbowl,2013 SB Win
0,Arizona Cardinals,10,6,0,No,No
1,Atlanta Falcons,4,12,0,No,No
2,Baltimore Ravens,8,8,0,No,No
3,Buffalo Bills,6,10,0,No,No
4,Carolina Panthers,12,4,0,No,No

### Merge Dataset with 2013 Data

In [64]:
nfl2013complete = pd.merge(off_def2013, wl2013, on='Team')

In [65]:
nfl2013complete.head()

,Team,2013 Off Tot Pts,2013 Off Pts/G,2013 Off RushYds,2013 Off RYds/G,2013 Off PassYds,2013 Off PYds/G,2013 Off TotYds,2013 Off Yds/G,2013 Def Tot Pts,...,2013 Def RYds/G,2013 Def PassYds,2013 Def PYds/G,2013 Def TotYds,2013 Def Yds/G,2013 Wins,2013 Loss,2013 Tie,2013 Superbowl,2013 SB Win
0,Arizona Cardinals,379,23.7,1540,96.2,4002,250.1,5542,346.4,324,...,84.4,3728,233.0,5079,317.4,10,6,0,No,No
1,Atlanta Falcons,353,22.1,1247,77.9,4243,265.2,5490,343.1,443,...,135.8,3897,243.6,6070,379.4,4,12,0,No,No
2,Baltimore Ravens,320,20.0,1328,83.0,3590,224.4,4918,307.4,352,...,105.4,3681,230.1,5368,335.5,8,8,0,No,No
3,Buffalo Bills,339,21.2,2307,144.2,3103,193.9,5410,338.1,388,...,128.9,3271,204.4,5334,333.4,6,10,0,No,No
4,Carolina Panthers,366,22.9,2026,126.6,3043,190.2,5069,316.8,241,...,86.9,3429,214.3,4820,301.2,12,4,0,No,No

### Save Dataset to Mac for future use

In [66]:
nfl2013complete.to_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2013complete.csv')