# Merge Years 2012-2020

### Import pandas package

In [1]:
import pandas as pd

## Import all datasets needed for merge

In [2]:
nfl2012_2019 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2012_2019merge.csv')
off2020 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2020_offense.csv')
def2020 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_off_def/NFL2020_defense.csv')
wl2020 = pd.read_csv('/Users/admin/Desktop/Final_Project/NFL_win_lose/NFL_2020_wl.csv')

In [3]:
nfl2012_2019.head()

,Unnamed: 0,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
0,0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,...,3213,200.8,5405,337.8,2012,5,11,0,No,No
1,1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,...,3878,242.4,5849,365.6,2012,13,3,0,No,No
2,2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,...,3650,228.1,5615,350.9,2012,10,6,0,Yes,Yes
3,3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,...,3473,217.1,5806,362.9,2012,6,10,0,No,No
4,4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,...,3568,223.0,5329,333.1,2012,7,9,0,No,No

In [4]:
off2020.head()

,Unnamed: 0,Team,2020 Off Tot Pts,2020 Off Pts/G,2020 Off RushYds,2020 Off RYds/G,2020 Off PassYds,2020 Off PYds/G,2020 Off TotYds,2020 Off Yds/G
0,5,Arizona CardinalsArizona,410,25.6,2237,139.8,3916,244.8,6153,384.6
1,17,Atlanta FalconsAtlanta,396,24.8,1532,95.8,4363,272.7,5895,368.4
2,18,Baltimore RavensBaltimore,468,29.2,3071,191.9,2739,171.2,5810,363.1
3,1,Buffalo BillsBuffalo,501,31.3,1723,107.7,4620,288.8,6343,396.4
4,20,Carolina PanthersCarolina,350,21.9,1704,106.5,3888,243.0,5592,349.5

In [5]:
def2020.head()

,Unnamed: 0,Team,2020 Def Tot/Pts,2020 Def Pts/G,2020 Def RushYds,2020 Def RYds/G,2020 Def PassYds,2020 Def PYds/G,2020 Def TotYds,2020 Def Yds/G
0,12,Arizona CardinalsArizona,367,22.9,2008,125.5,3623,226.4,5631,351.9
1,28,Atlanta FalconsAtlanta,414,25.9,1677,104.8,4697,293.6,6374,398.4
2,6,Baltimore RavensBaltimore,303,18.9,1740,108.8,3536,221.0,5276,329.8
3,13,Buffalo BillsBuffalo,375,23.4,1914,119.6,3726,232.9,5640,352.5
4,17,Carolina PanthersCarolina,402,25.1,1936,121.0,3825,239.1,5761,360.1

In [6]:
wl2020.head()

   Unnamed: 0               Team  Wins  Losses  Tie Superbowl SB Win  Year
0          16  Arizona Cardinals     8       8    0        No     No  2020
1           2    Atlanta Falcons     4      12    0        No     No  2020
2          21   Baltimore Ravens    11       5    0        No     No  2020
3          29      Buffalo Bills    13       3    0        No     No  2020
4           6  Carolina Panthers     5      11    0        No     No  2020

### Drop unnamed column in all datasets

In [7]:
nfl2012_2019 = nfl2012_2019.iloc[:, 1:]
off2020 = off2020.iloc[:, 1:]
def2020 = def2020.iloc[:, 1:]
wl2020 = wl2020.iloc[:, 1:]

In [8]:
nfl2012_2019.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,...,3213,200.8,5405,337.8,2012,5,11,0,No,No
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,...,3878,242.4,5849,365.6,2012,13,3,0,No,No
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,...,3650,228.1,5615,350.9,2012,10,6,0,Yes,Yes
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,...,3473,217.1,5806,362.9,2012,6,10,0,No,No
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,...,3568,223.0,5329,333.1,2012,7,9,0,No,No

In [9]:
off2020.head()

,Team,2020 Off Tot Pts,2020 Off Pts/G,2020 Off RushYds,2020 Off RYds/G,2020 Off PassYds,2020 Off PYds/G,2020 Off TotYds,2020 Off Yds/G
0,Arizona CardinalsArizona,410,25.6,2237,139.8,3916,244.8,6153,384.6
1,Atlanta FalconsAtlanta,396,24.8,1532,95.8,4363,272.7,5895,368.4
2,Baltimore RavensBaltimore,468,29.2,3071,191.9,2739,171.2,5810,363.1
3,Buffalo BillsBuffalo,501,31.3,1723,107.7,4620,288.8,6343,396.4
4,Carolina PanthersCarolina,350,21.9,1704,106.5,3888,243.0,5592,349.5

In [10]:
def2020.head()

,Team,2020 Def Tot/Pts,2020 Def Pts/G,2020 Def RushYds,2020 Def RYds/G,2020 Def PassYds,2020 Def PYds/G,2020 Def TotYds,2020 Def Yds/G
0,Arizona CardinalsArizona,367,22.9,2008,125.5,3623,226.4,5631,351.9
1,Atlanta FalconsAtlanta,414,25.9,1677,104.8,4697,293.6,6374,398.4
2,Baltimore RavensBaltimore,303,18.9,1740,108.8,3536,221.0,5276,329.8
3,Buffalo BillsBuffalo,375,23.4,1914,119.6,3726,232.9,5640,352.5
4,Carolina PanthersCarolina,402,25.1,1936,121.0,3825,239.1,5761,360.1

In [11]:
wl2020.head()

                Team  Wins  Losses  Tie Superbowl SB Win  Year
0  Arizona Cardinals     8       8    0        No     No  2020
1    Atlanta Falcons     4      12    0        No     No  2020
2   Baltimore Ravens    11       5    0        No     No  2020
3      Buffalo Bills    13       3    0        No     No  2020
4  Carolina Panthers     5      11    0        No     No  2020

### Rename columns in off/def dataset

In [12]:
offense2020 = off2020.rename(columns ={"2020 Off Tot Pts": "Off Tot/Pts", "2020 Off Pts/G": "Off Pts/G",
                                                     "2020 Off RushYds": "Off RushYds", "2020 Off RYds/G": "Off RYds/G",
                                                     "2020 Off PassYds": "Off PassYds", "2020 Off PYds/G": "Off PYds/G",
                                                     "2020 Off TotYds": "Off TotYds", "2020 Off Yds/G": "Off Yds/G"})
defense2020 = def2020.rename(columns ={"2020 Def Tot/Pts": "Def Tot/Pts", "2020 Def Pts/G": "Def Pts/G",
                                                     "2020 Def RushYds": "Def RushYds", "2020 Def RYds/G": "Def RYds/G",
                                                     "2020 Def PassYds": "Def PassYds", "2020 Def PYds/G": "Def PYds/G",
                                                     "2020 Def TotYds": "Def TotYds", "2020 Def Yds/G": "Def Yds/G"})

In [13]:
offense2020.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G
0,Arizona CardinalsArizona,410,25.6,2237,139.8,3916,244.8,6153,384.6
1,Atlanta FalconsAtlanta,396,24.8,1532,95.8,4363,272.7,5895,368.4
2,Baltimore RavensBaltimore,468,29.2,3071,191.9,2739,171.2,5810,363.1
3,Buffalo BillsBuffalo,501,31.3,1723,107.7,4620,288.8,6343,396.4
4,Carolina PanthersCarolina,350,21.9,1704,106.5,3888,243.0,5592,349.5

In [14]:
defense2020.head()

,Team,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
0,Arizona CardinalsArizona,367,22.9,2008,125.5,3623,226.4,5631,351.9
1,Atlanta FalconsAtlanta,414,25.9,1677,104.8,4697,293.6,6374,398.4
2,Baltimore RavensBaltimore,303,18.9,1740,108.8,3536,221.0,5276,329.8
3,Buffalo BillsBuffalo,375,23.4,1914,119.6,3726,232.9,5640,352.5
4,Carolina PanthersCarolina,402,25.1,1936,121.0,3825,239.1,5761,360.1

### Merge Offense and Defense Data

In [15]:
off_def2020 = pd.merge(offense2020, defense2020, on='Team')

In [17]:
off_def2020.head(32)

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
0,Arizona CardinalsArizona,410,25.6,2237,139.8,3916,244.8,6153,384.6,367,22.9,2008,125.5,3623,226.4,5631,351.9
1,Atlanta FalconsAtlanta,396,24.8,1532,95.8,4363,272.7,5895,368.4,414,25.9,1677,104.8,4697,293.6,6374,398.4
2,Baltimore RavensBaltimore,468,29.2,3071,191.9,2739,171.2,5810,363.1,303,18.9,1740,108.8,3536,221.0,5276,329.8
3,Buffalo BillsBuffalo,501,31.3,1723,107.7,4620,288.8,6343,396.4,375,23.4,1914,119.6,3726,232.9,5640,352.5
4,Carolina PanthersCarolina,350,21.9,1704,106.5,3888,243.0,5592,349.5,402,25.1,1936,121.0,3825,239.1,5761,360.1
5,Chicago BearsChicago,372,23.2,1647,102.9,3655,228.4,5302,331.4,370,23.1,1814,113.4,3705,231.6,5519,344.9
6,Cincinnati BengalsCincinnati,311,19.4,1668,104.2,3448,215.5,5116,319.8,424,26.5,2368,148.0,3859,241.2,6227,389.2
7,Cleveland BrownsCleveland,408,25.5,2374,148.4,3539,221.2,5913,369.6,419,26.2,1773,110.8,3962,247.6,5735,358.4
8,Dallas CowboysDallas,395,24.7,1788,111.8,4161,260.1,5949,371.8,473,29.6,2541,158.8,3642,227.6,6183,386.4
9,Denver BroncosDenver,323,20.2,1918,119.9,3451,215.7,5369,335.6,446,27.9,2080,130.0,3807,237.9,5887,367.9
10,Detroit LionsDetroit,377,23.6,1499,93.7,4104,256.5,5603,350.2,519,32.4,2158,134.9,4558,284.9,6716,419.8
11,Green Bay PackersGreen Bay,509,31.8,2118,132.4,4106,256.6,6224,389.0,369,23.1,1805,112.8,3539,221.2,5344,334.0
12,Houston TexansHouston,384,24.0,1466,91.6,4538,283.6,6004,375.2,464,29.0,2564,160.2,4104,256.5,6668,416.8
13,Indianapolis ColtsIndianapolis,451,28.2,1996,124.8,4053,253.3,6049,378.1,362,22.6,1448,90.5,3866,241.6,5314,332.1
14,Jacksonville JaguarsJacksonville,306,19.1,1519,94.9,3699,231.2,5218,326.1,492,30.8,2452,153.2,4231,264.4,6683,417.7
15,Kansas City ChiefsKansas City,473,29.6,1799,112.4,4854,303.4,6653,415.8,362,22.6,1954,122.1,3779,236.2,5733,358.3
16,Las Vegas RaidersLas Vegas,434,27.1,1916,119.8,4217,263.6,6133,383.3,478,29.9,2013,125.8,4212,263.2,6225,389.1
17,Los Angeles ChargersLA Chargers,384,24.0,1784,111.5,4329,270.6,6113,382.1,426,26.6,1917,119.8,3578,223.6,5495,343.4
18,Los Angeles RamsLA Rams,372,23.2,2018,126.1,4014,250.9,6032,377.0,296,18.5,1460,91.2,3051,190.7,4511,281.9
19,Miami DolphinsMiami,404,25.2,1688,105.5,3736,233.5,5424,339.0,338,21.1,1862,116.4,4024,251.5,5886,367.9
20,Minnesota VikingsMinnesota,430,26.9,2283,142.7,4009,250.6,6292,393.2,475,29.7,2151,134.4,4141,258.8,6292,393.2
21,New England PatriotsNew England,326,20.4,2346,146.6,2890,180.6,5236,327.2,353,22.1,2103,131.4,3557,222.3,5660,353.8
22,New Orleans SaintsNew Orleans,482,30.1,2265,141.6,3758,234.9,6023,376.4,337,21.1,1502,93.9,3472,217.0,4974,310.9
23,New York GiantsNY Giants,280,17.5,1768,110.5,3026,189.1,4794,299.6,357,22.3,1782,111.4,3807,237.9,5589,349.3
24,New York JetsNY Jets,243,15.2,1683,105.2,2796,174.8,4479,279.9,457,28.6,1792,112.0,4409,275.6,6201,387.6
25,Philadelphia EaglesPhiladelphia,334,20.9,2027,126.7,3327,207.9,5354,334.6,418,26.1,2012,125.8,3798,237.4,5810,363.1
26,Pittsburgh SteelersPittsburgh,416,26.0,1351,84.4,4003,250.2,5354,334.6,312,19.5,1783,111.4,3110,194.4,4893,305.8
27,San Francisco 49ersSan Francisco,376,23.5,1889,118.1,4033,252.1,5922,370.1,390,24.4,1703,106.4,3327,207.9,5030,314.4
28,Seattle SeahawksSeattle,459,28.7,1971,123.2,3941,246.3,5912,369.5,371,23.2,1529,95.6,4560,285.0,6089,380.6
29,Tampa Bay BuccaneersTampa Bay,492,30.8,1519,94.9,4626,289.1,6145,384.1,355,22.2,1289,80.6,3945,246.6,5234,327.1
30,Tennessee TitansTennessee,491,30.7,2690,168.1,3653,228.3,6343,396.4,439,27.4,1933,120.8,4439,277.4,6372,398.2
31,Washington Football TeamWashington,335,20.9,1611,100.7,3465,216.6,5076,317.2,329,20.6,1805,112.8,3068,191.8,4873,304.6

### Rename Teams to match merge data

In [18]:
teamnames20 = {'Arizona CardinalsArizona': 'Arizona Cardinals', 'Atlanta FalconsAtlanta': 'Atlanta Falcons', 
             'Baltimore RavensBaltimore': 'Baltimore Ravens', 'Buffalo BillsBuffalo': 'Buffalo Bills',
            'Carolina PanthersCarolina': 'Carolina Panthers', 'Chicago BearsChicago': 'Chicago Bears',
            'Cincinnati BengalsCincinnati': 'Cincinnati Bengals', 'Cleveland BrownsCleveland': 'Cleveland Browns',
            'Dallas CowboysDallas': 'Dallas Cowboys', 'Denver BroncosDenver': 'Denver Broncos', 
             'Detroit LionsDetroit': 'Detroit Lions', 'Green Bay PackersGreen Bay': 'Green Bay Packers',
            'Houston TexansHouston': 'Houston Texans', 'Indianapolis ColtsIndianapolis': 'Indianapolis Colts',
            'Jacksonville JaguarsJacksonville': 'Jacksonville Jaguars', 'Kansas City ChiefsKansas City': 'Kansas City Chiefs',
            'Los Angeles ChargersLA Chargers': 'Los Angeles Chargers', 'Los Angeles RamsLA Rams': 'Los Angeles Rams',
            'Miami DolphinsMiami': 'Miami Dolphins', 'Minnesota VikingsMinnesota': 'Minnesota Vikings', 
            'New England PatriotsNew England': 'New England Patriots', 'New Orleans SaintsNew Orleans': 'New Orleans Saints',
            'New York GiantsNY Giants': 'New York Giants', 'New York JetsNY Jets': 'New York Jets', 
            'Las Vegas RaidersLas Vegas': 'Las Vegas Raiders', 'Philadelphia EaglesPhiladelphia': 'Philadelphia Eagles',
            'Pittsburgh SteelersPittsburgh': 'Pittsburgh Steelers',
            'San Francisco 49ersSan Francisco': 'San Francisco 49ers', 'Seattle SeahawksSeattle': 'Seattle Seahawks', 
            'Tampa Bay BuccaneersTampa Bay': 'Tampa Bay Buccaneers', 'Tennessee TitansTennessee': 'Tennessee Titans',
            'Washington Football TeamWashington': 'Washington Commanders'}
off_def2020['Team'] = off_def2020['Team'].replace(teamnames20)

In [19]:
off_def2020.tail(16)

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
16,Las Vegas Raiders,434,27.1,1916,119.8,4217,263.6,6133,383.3,478,29.9,2013,125.8,4212,263.2,6225,389.1
17,Los Angeles Chargers,384,24.0,1784,111.5,4329,270.6,6113,382.1,426,26.6,1917,119.8,3578,223.6,5495,343.4
18,Los Angeles Rams,372,23.2,2018,126.1,4014,250.9,6032,377.0,296,18.5,1460,91.2,3051,190.7,4511,281.9
19,Miami Dolphins,404,25.2,1688,105.5,3736,233.5,5424,339.0,338,21.1,1862,116.4,4024,251.5,5886,367.9
20,Minnesota Vikings,430,26.9,2283,142.7,4009,250.6,6292,393.2,475,29.7,2151,134.4,4141,258.8,6292,393.2
21,New England Patriots,326,20.4,2346,146.6,2890,180.6,5236,327.2,353,22.1,2103,131.4,3557,222.3,5660,353.8
22,New Orleans Saints,482,30.1,2265,141.6,3758,234.9,6023,376.4,337,21.1,1502,93.9,3472,217.0,4974,310.9
23,New York Giants,280,17.5,1768,110.5,3026,189.1,4794,299.6,357,22.3,1782,111.4,3807,237.9,5589,349.3
24,New York Jets,243,15.2,1683,105.2,2796,174.8,4479,279.9,457,28.6,1792,112.0,4409,275.6,6201,387.6
25,Philadelphia Eagles,334,20.9,2027,126.7,3327,207.9,5354,334.6,418,26.1,2012,125.8,3798,237.4,5810,363.1
26,Pittsburgh Steelers,416,26.0,1351,84.4,4003,250.2,5354,334.6,312,19.5,1783,111.4,3110,194.4,4893,305.8
27,San Francisco 49ers,376,23.5,1889,118.1,4033,252.1,5922,370.1,390,24.4,1703,106.4,3327,207.9,5030,314.4
28,Seattle Seahawks,459,28.7,1971,123.2,3941,246.3,5912,369.5,371,23.2,1529,95.6,4560,285.0,6089,380.6
29,Tampa Bay Buccaneers,492,30.8,1519,94.9,4626,289.1,6145,384.1,355,22.2,1289,80.6,3945,246.6,5234,327.1
30,Tennessee Titans,491,30.7,2690,168.1,3653,228.3,6343,396.4,439,27.4,1933,120.8,4439,277.4,6372,398.2
31,Washington Commanders,335,20.9,1611,100.7,3465,216.6,5076,317.2,329,20.6,1805,112.8,3068,191.8,4873,304.6

### Put Dataset in Team Ascending Order

In [20]:
off_def2020 = off_def2020.sort_values("Team")

In [21]:
off_def2020.tail(16)

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,Def Pts/G,Def RushYds,Def RYds/G,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G
16,Las Vegas Raiders,434,27.1,1916,119.8,4217,263.6,6133,383.3,478,29.9,2013,125.8,4212,263.2,6225,389.1
17,Los Angeles Chargers,384,24.0,1784,111.5,4329,270.6,6113,382.1,426,26.6,1917,119.8,3578,223.6,5495,343.4
18,Los Angeles Rams,372,23.2,2018,126.1,4014,250.9,6032,377.0,296,18.5,1460,91.2,3051,190.7,4511,281.9
19,Miami Dolphins,404,25.2,1688,105.5,3736,233.5,5424,339.0,338,21.1,1862,116.4,4024,251.5,5886,367.9
20,Minnesota Vikings,430,26.9,2283,142.7,4009,250.6,6292,393.2,475,29.7,2151,134.4,4141,258.8,6292,393.2
21,New England Patriots,326,20.4,2346,146.6,2890,180.6,5236,327.2,353,22.1,2103,131.4,3557,222.3,5660,353.8
22,New Orleans Saints,482,30.1,2265,141.6,3758,234.9,6023,376.4,337,21.1,1502,93.9,3472,217.0,4974,310.9
23,New York Giants,280,17.5,1768,110.5,3026,189.1,4794,299.6,357,22.3,1782,111.4,3807,237.9,5589,349.3
24,New York Jets,243,15.2,1683,105.2,2796,174.8,4479,279.9,457,28.6,1792,112.0,4409,275.6,6201,387.6
25,Philadelphia Eagles,334,20.9,2027,126.7,3327,207.9,5354,334.6,418,26.1,2012,125.8,3798,237.4,5810,363.1
26,Pittsburgh Steelers,416,26.0,1351,84.4,4003,250.2,5354,334.6,312,19.5,1783,111.4,3110,194.4,4893,305.8
27,San Francisco 49ers,376,23.5,1889,118.1,4033,252.1,5922,370.1,390,24.4,1703,106.4,3327,207.9,5030,314.4
28,Seattle Seahawks,459,28.7,1971,123.2,3941,246.3,5912,369.5,371,23.2,1529,95.6,4560,285.0,6089,380.6
29,Tampa Bay Buccaneers,492,30.8,1519,94.9,4626,289.1,6145,384.1,355,22.2,1289,80.6,3945,246.6,5234,327.1
30,Tennessee Titans,491,30.7,2690,168.1,3653,228.3,6343,396.4,439,27.4,1933,120.8,4439,277.4,6372,398.2
31,Washington Commanders,335,20.9,1611,100.7,3465,216.6,5076,317.2,329,20.6,1805,112.8,3068,191.8,4873,304.6

### Merge with Win/Loss Data

In [22]:
nfl2020 = pd.merge(off_def2020, wl2020, on="Team")

In [23]:
nfl2020.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Wins,Losses,Tie,Superbowl,SB Win,Year
0,Arizona Cardinals,410,25.6,2237,139.8,3916,244.8,6153,384.6,367,...,3623,226.4,5631,351.9,8,8,0,No,No,2020
1,Atlanta Falcons,396,24.8,1532,95.8,4363,272.7,5895,368.4,414,...,4697,293.6,6374,398.4,4,12,0,No,No,2020
2,Baltimore Ravens,468,29.2,3071,191.9,2739,171.2,5810,363.1,303,...,3536,221.0,5276,329.8,11,5,0,No,No,2020
3,Buffalo Bills,501,31.3,1723,107.7,4620,288.8,6343,396.4,375,...,3726,232.9,5640,352.5,13,3,0,No,No,2020
4,Carolina Panthers,350,21.9,1704,106.5,3888,243.0,5592,349.5,402,...,3825,239.1,5761,360.1,5,11,0,No,No,2020

### Save Dataset to Mac for future use

In [24]:
nfl2020.to_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2020complete.csv')

### Merge 2012-2020 Data

In [25]:
nfl2012_2020 = pd.concat([nfl2012_2019, nfl2020], axis=0, join='outer', ignore_index='True')

In [26]:
nfl2012_2020.head()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
0,Arizona Cardinals,250,15.6,1204,75.2,3005,187.8,4209,263.1,357,...,3213,200.8,5405,337.8,2012,5,11,0,No,No
1,Atlanta Falcons,419,26.2,1397,87.3,4509,281.8,5906,369.1,299,...,3878,242.4,5849,365.6,2012,13,3,0,No,No
2,Baltimore Ravens,398,24.9,1901,118.8,3739,233.7,5640,352.5,344,...,3650,228.1,5615,350.9,2012,10,6,0,Yes,Yes
3,Buffalo Bills,344,21.5,2217,138.6,3269,204.3,5486,342.9,435,...,3473,217.1,5806,362.9,2012,6,10,0,No,No
4,Carolina Panthers,357,22.3,2088,130.5,3683,230.2,5771,360.7,363,...,3568,223.0,5329,333.1,2012,7,9,0,No,No

In [27]:
nfl2012_2020.tail()

,Team,Off Tot/Pts,Off Pts/G,Off RushYds,Off RYds/G,Off PassYds,Off PYds/G,Off TotYds,Off Yds/G,Def Tot/Pts,...,Def PassYds,Def PYds/G,Def TotYds,Def Yds/G,Year,Wins,Losses,Tie,Superbowl,SB Win
282,San Francisco 49ers,376,23.5,1889,118.1,4033,252.1,5922,370.1,390,...,3327,207.9,5030,314.4,2020,6,10,0,No,No
283,Seattle Seahawks,459,28.7,1971,123.2,3941,246.3,5912,369.5,371,...,4560,285.0,6089,380.6,2020,12,4,0,No,No
284,Tampa Bay Buccaneers,492,30.8,1519,94.9,4626,289.1,6145,384.1,355,...,3945,246.6,5234,327.1,2020,11,5,0,Yes,Yes
285,Tennessee Titans,491,30.7,2690,168.1,3653,228.3,6343,396.4,439,...,4439,277.4,6372,398.2,2020,11,5,0,No,No
286,Washington Commanders,335,20.9,1611,100.7,3465,216.6,5076,317.2,329,...,3068,191.8,4873,304.6,2020,7,9,0,No,No

### Save Dataset to Mac for future use

In [28]:
nfl2012_2020.to_csv('/Users/admin/Desktop/Final_Project/NFL_merged/nfl2012_2020merge.csv')